---
- name: Deploy PetClinic Application
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Build the Docker image
      community.docker.docker_image:
        build:
          path: "."
          tag: "petclinic-app:{{ build_id }}"
        source: build

    - name: Run the Docker container
      community.docker.docker_container:
        name: "petclinic"
        image: "petclinic-app:{{ build_id }}"
        state: started
        restart_policy: always
        published_ports:
          - "8081:8080"
