---
- name: Deploy PetClinic Application
  hosts: all
  tasks:
    - name: Copy PetClinic JAR to the target server
      synchronize:
        src: "/var/jenkins_home/workspace/Pet Clinic/target/spring-petclinic-3.2.0-SNAPSHOT.jar"
        dest: "/petclinic.jar"
        rsync_path: "/usr/bin/rsync"
        mode: push
      when: inventory_hostname == 'petclinic-host'
      delegate_to: localhost

    - debug:
        msg: "The inventory hostname is {{ inventory_hostname }}"

    - name: Start the PetClinic Java application
      shell: |
        nohup java -jar /petclinic.jar > /petclinic.log 2>&1 &
      async: 20
      poll: 0
      when: inventory_hostname == 'petclinic-host'
