---
- name: Deploy PetClinic Application
  hosts: petclinic-host
  tasks:
    - name: Find PetClinic JAR file
      find:
        paths: "/var/jenkins_home/workspace/Pet Clinic/target/"
        patterns: 'spring-petclinic-*.jar'
      register: jar_files

    - name: Copy PetClinic JAR to the target server
      copy:
        src: "{{ item.path }}"
        dest: "/app/petclinic.jar"
      with_items: "{{ jar_files.files }}"
      when: jar_files.matched > 0

    - name: Start the PetClinic Java application
      shell: |
        nohup java -jar /app/petclinic.jar > /app/petclinic.log 2>&1 &
      async: 20
      poll: 0
