---
- name: Deploy PetClinic Application
  hosts: all
  tasks:
    - name: Copy PetClinic JAR to the target server
      synchronize:
        src: "/var/jenkins_home/workspace/Pet Clinic/target/spring-petclinic-3.2.0-SNAPSHOT.jar"
        dest: "/app/petclinic.jar"
        rsync_path: "/usr/bin/rsync"
        mode: push

    - debug:
        msg: "The inventory hostname is {{ inventory_hostname }}"

    - name: Start the PetClinic Java application
      shell: |
        nohup java -jar /app/petclinic.jar -server.port=8081 > /petclinic.log 2>&1 &
      async: 20
      poll: 0
